com.instana.plugin.mysql:
  user: 'instana_mon_user'
  password:
    configuration_from:
      type: env
      env_name: INSTANA_MYSQL_USER
  schema_excludes: ['INFORMATION_SCHEMA', 'PERFORMANCE_SCHEMA']
